name: Deploy docs
on:
  push:
    branches: 
      - main
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      
      - run: yarn --frozen-lockfile
      
      - run: yarn build
        env: 
          TURBO_TOKEN: JOOw8oLuaG2KhNM2xIKIa9jc
          TURBO_TEAM: khazaf

      - name: Deploy storybook
        working-directory: ./packages/docs
        run: yarn deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
